"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from datetime import datetime, timedelta

import main

from specleft import specleft

from conftest import (
    create_document,
    delegate_review,
    review_document,
    revoke_delegation,
    submit_document,
)

# =============================================================================
# Feature: 3: Delegation
# ID: feature-3-delegation
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="delegate-review-to-substitute-with-expiry-date",
)
def test_delegate_review_to_substitute_with_expiry_date(
    client, author, reviewer, additional_reviewer
):
    """Delegate review to substitute with expiry date

    Priority: medium
    """
    with specleft.step("Given a reviewer assigned to a document"):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])

    with specleft.step("When they delegate to a substitute with an expiry date"):
        expires_at = (datetime.utcnow() + timedelta(days=1)).isoformat()
        response = delegate_review(
            client,
            document["id"],
            reviewer["id"],
            additional_reviewer["id"],
            expires_at,
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step(
        "Then the substitute is granted review permissions for that document"
    ):
        response = review_document(
            client, document["id"], additional_reviewer["id"], "approve"
        )
        assert response.status_code == 200

    with specleft.step("And the delegation record includes the expiry timestamp"):
        with main.SessionLocal() as session:
            delegation = (
                session.execute(
                    main.select(main.Delegation)
                    .where(main.Delegation.document_id == document["id"])
                    .order_by(main.Delegation.created_at.desc())
                )
                .scalars()
                .first()
            )
            assert delegation is not None
            assert delegation.expires_at is not None


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="delegator-can-revoke-delegation-before-expiry",
)
def test_delegator_can_revoke_delegation_before_expiry(
    client, author, reviewer, additional_reviewer
):
    """Delegator can revoke delegation before expiry

    Priority: medium
    """
    with specleft.step("Given an active delegation"):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])
        expires_at = (datetime.utcnow() + timedelta(days=1)).isoformat()
        response = delegate_review(
            client,
            document["id"],
            reviewer["id"],
            additional_reviewer["id"],
            expires_at,
        )
        assert response.status_code == 200

    with specleft.step("When the delegator revokes the delegation"):
        response = revoke_delegation(client, document["id"], reviewer["id"])
        assert response.status_code == 200

    with specleft.step("Then the substitute loses review permissions immediately"):
        response = review_document(
            client, document["id"], additional_reviewer["id"], "approve"
        )
        assert response.status_code == 403

    with specleft.step("And subsequent actions by the substitute are rejected"):
        assert response.json()["detail"] == "reviewer not assigned"


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="expired-delegation-is-rejected",
)
def test_expired_delegation_is_rejected(client, author, reviewer, additional_reviewer):
    """Expired delegation is rejected

    Priority: medium
    """
    with specleft.step("Given a delegation that has passed its expiry date"):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])
        expires_at = (datetime.utcnow() - timedelta(days=1)).isoformat()
        response = delegate_review(
            client,
            document["id"],
            reviewer["id"],
            additional_reviewer["id"],
            expires_at,
        )
        assert response.status_code == 200

    with specleft.step("When the substitute attempts to approve the document"):
        response = review_document(
            client, document["id"], additional_reviewer["id"], "approve"
        )

    with specleft.step("Then the approval is rejected"):
        assert response.status_code == 400

    with specleft.step(
        "And an error is returned indicating the delegation has expired"
    ):
        assert response.json()["detail"] == "delegation has expired"


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="notes-2",
    skip=True,
    reason="Priority note only",
)
def test_notes_2():
    """Notes

    Priority: high
    """


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="prevent-delegation-chain",
)
def test_prevent_delegation_chain(client, author, reviewer, additional_reviewer):
    """Prevent delegation chain

    Priority: medium
    """
    with specleft.step("Given a substitute who has been delegated review authority"):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])
        expires_at = (datetime.utcnow() + timedelta(days=1)).isoformat()
        response = delegate_review(
            client,
            document["id"],
            reviewer["id"],
            additional_reviewer["id"],
            expires_at,
        )
        assert response.status_code == 200

    with specleft.step("When the substitute attempts to delegate to another person"):
        response = delegate_review(
            client,
            document["id"],
            additional_reviewer["id"],
            author["id"],
            (datetime.utcnow() + timedelta(days=1)).isoformat(),
        )

    with specleft.step("Then the delegation is rejected"):
        assert response.status_code == 400

    with specleft.step(
        "And an error is returned indicating re-delegation is not permitted"
    ):
        assert response.json()["detail"] == "re-delegation not permitted"


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="substitute-can-approve-on-behalf-of-delegator",
)
def test_substitute_can_approve_on_behalf_of_delegator(
    client, author, reviewer, additional_reviewer
):
    """Substitute can approve on behalf of delegator

    Priority: medium
    """
    with specleft.step("Given a valid delegation that has not expired"):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])
        expires_at = (datetime.utcnow() + timedelta(days=1)).isoformat()
        response = delegate_review(
            client,
            document["id"],
            reviewer["id"],
            additional_reviewer["id"],
            expires_at,
        )
        assert response.status_code == 200

    with specleft.step("When the substitute approves the document"):
        response = review_document(
            client, document["id"], additional_reviewer["id"], "approve"
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step(
        "Then the approval is recorded as the substitute acting on behalf of the delegator"
    ):
        reviewers = payload["review_cycles"][0]["reviewers"]
        reviewer_status = next(
            item for item in reviewers if item["reviewer_id"] == reviewer["id"]
        )
        assert reviewer_status["decided_by_id"] == additional_reviewer["id"]

    with specleft.step("And the delegator's review requirement is satisfied"):
        assert reviewer_status["decision"] == "approve"
