"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft

from conftest import create_document, review_document, submit_document


# =============================================================================
# Feature: 2: Multi-Reviewer Approval
# ID: feature-2-multi-reviewer-approval
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="notes-1",
    skip=True,
    reason="Priority note only",
)
def test_notes_1():
    """Notes

    Priority: critical
    """


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="prevent-duplicate-approval-from-same-reviewer",
)
def test_prevent_duplicate_approval_from_same_reviewer(client, author, reviewer):
    """Prevent duplicate approval from same reviewer

    Priority: medium
    """
    with specleft.step("Given a reviewer who has already approved a document"):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])
        response = review_document(client, document["id"], reviewer["id"], "approve")
        assert response.status_code == 200

    with specleft.step("When they attempt to approve the same document again"):
        response = review_document(client, document["id"], reviewer["id"], "approve")

    with specleft.step("Then the request is rejected"):
        assert response.status_code == 400

    with specleft.step(
        "And an error is returned indicating they have already submitted a decision"
    ):
        assert response.json()["detail"] == "decision already submitted"


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="reject-if-any-reviewer-rejects",
)
def test_reject_if_any_reviewer_rejects(client, author, reviewer, additional_reviewer):
    """Reject if any reviewer rejects

    Priority: medium
    """
    with specleft.step('Given a document in "review" status with multiple reviewers'):
        document = create_document(
            client,
            author["id"],
            [reviewer["id"], additional_reviewer["id"]],
        )
        submit_document(client, document["id"], author["id"])

    with specleft.step("When one reviewer rejects the document"):
        response = review_document(
            client, document["id"], reviewer["id"], "reject", reason="No"
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step('Then the document status changes to "rejected"'):
        assert payload["status"] == "rejected"

    with specleft.step("And remaining reviewers are no longer required to act"):
        assert payload["status"] == "rejected"


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="require-all-assigned-reviewers-to-approve",
)
def test_require_all_assigned_reviewers_to_approve(
    client, author, reviewer, additional_reviewer, third_reviewer
):
    """Require all assigned reviewers to approve

    Priority: medium
    """
    reviewer_ids = [reviewer["id"], additional_reviewer["id"], third_reviewer["id"]]
    with specleft.step(
        'Given a document in "review" status with three assigned reviewers'
    ):
        document = create_document(client, author["id"], reviewer_ids)
        submit_document(client, document["id"], author["id"])

    with specleft.step("When only two reviewers have approved"):
        response = review_document(client, document["id"], reviewer["id"], "approve")
        assert response.status_code == 200
        response = review_document(
            client, document["id"], additional_reviewer["id"], "approve"
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step('Then the document remains in "review" status'):
        assert payload["status"] == "review"

    with specleft.step("And the pending reviewer is visible in the status response"):
        assert third_reviewer["id"] in payload["pending_reviewer_ids"]


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="track-individual-reviewer-decisions-with-timestamps",
)
def test_track_individual_reviewer_decisions_with_timestamps(client, author, reviewer):
    """Track individual reviewer decisions with timestamps

    Priority: medium
    """
    with specleft.step('Given a document in "review" status'):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])

    with specleft.step("When a reviewer submits their decision"):
        response = review_document(client, document["id"], reviewer["id"], "approve")
        assert response.status_code == 200
        payload = response.json()

    with specleft.step(
        "Then the decision is recorded with the reviewer ID and timestamp"
    ):
        reviewer_status = payload["review_cycles"][0]["reviewers"][0]
        assert reviewer_status["reviewer_id"] == reviewer["id"]
        assert reviewer_status["decision_at"] is not None

    with specleft.step("And the decision is visible in the document review history"):
        history = payload["review_cycles"][0]["reviewers"]
        assert history[0]["decision"] == "approve"
