"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft

from conftest import create_document, review_document, submit_document, update_document


# =============================================================================
# Feature: 1: Document Lifecycle
# ID: feature-1-document-lifecycle
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="approve-document-with-single-reviewer",
)
def test_approve_document_with_single_reviewer(client, author, reviewer):
    """Approve document with single reviewer

    Priority: medium
    """
    with specleft.step(
        'Given a document in "review" status with one assigned reviewer'
    ):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])

    with specleft.step("When the reviewer approves the document"):
        response = review_document(client, document["id"], reviewer["id"], "approve")
        assert response.status_code == 200
        payload = response.json()

    with specleft.step('Then the document status changes to "approved"'):
        assert payload["status"] == "approved"

    with specleft.step("And the approval is recorded with a timestamp"):
        reviewer_status = payload["review_cycles"][0]["reviewers"][0]
        assert reviewer_status["decision_at"] is not None


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="create-document-as-draft",
)
def test_create_document_as_draft(client, author, reviewer):
    """Create document as draft

    Priority: medium
    """
    with specleft.step("Given a user with author permissions"):
        author_id = author["id"]

    with specleft.step("When they create a new document"):
        response = client.post(
            "/documents",
            json={
                "author_id": author_id,
                "title": "Doc",
                "content": "Content",
                "reviewer_ids": [reviewer["id"]],
                "escalation_chain": [],
                "escalation_timeout_seconds": 3600,
                "max_escalation_depth": 3,
            },
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step('Then the document is created with status "draft"'):
        assert payload["status"] == "draft"

    with specleft.step("And the document is assigned to the author"):
        assert payload["author_id"] == author_id


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="notes",
    skip=True,
    reason="Priority note only",
)
def test_notes():
    """Notes

    Priority: critical
    """


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="prevent-edits-to-approved-documents",
)
def test_prevent_edits_to_approved_documents(client, author, reviewer):
    """Prevent edits to approved documents

    Priority: medium
    """
    with specleft.step('Given a document in "approved" status'):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])
        response = review_document(client, document["id"], reviewer["id"], "approve")
        assert response.status_code == 200

    with specleft.step("When any user attempts to edit the document"):
        response = update_document(client, document["id"], author["id"], title="New")

    with specleft.step("Then the edit is rejected"):
        assert response.status_code == 400

    with specleft.step("And an error is returned indicating the document is locked"):
        assert response.json()["detail"] == "document is locked"


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="prevent-edits-to-documents-under-review",
)
def test_prevent_edits_to_documents_under_review(client, author, reviewer):
    """Prevent edits to documents under review

    Priority: medium
    """
    with specleft.step('Given a document in "review" status'):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])

    with specleft.step("When the author attempts to edit the document"):
        response = update_document(
            client, document["id"], author["id"], content="Updated"
        )

    with specleft.step("Then the edit is rejected"):
        assert response.status_code == 400

    with specleft.step(
        "And an error is returned indicating the document is under review"
    ):
        assert response.json()["detail"] == "document is under review"


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="reject-document-with-reason",
)
def test_reject_document_with_reason(client, author, reviewer):
    """Reject document with reason

    Priority: medium
    """
    with specleft.step('Given a document in "review" status'):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])

    with specleft.step("When a reviewer rejects the document"):
        response = review_document(
            client, document["id"], reviewer["id"], "reject", reason="Bad"
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step('Then the document status changes to "rejected"'):
        assert payload["status"] == "rejected"

    with specleft.step("And the rejection reason is recorded"):
        reviewer_status = payload["review_cycles"][0]["reviewers"][0]
        assert reviewer_status["decision_reason"] == "Bad"


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="submit-document-for-review",
)
def test_submit_document_for_review(client, author, reviewer):
    """Submit document for review

    Priority: medium
    """
    with specleft.step('Given a document in "draft" status'):
        document = create_document(client, author["id"], [reviewer["id"]])

    with specleft.step("When the author submits it for review"):
        payload = submit_document(client, document["id"], author["id"])

    with specleft.step('Then the document status changes to "review"'):
        assert payload["status"] == "review"

    with specleft.step("And all assigned reviewers are notified"):
        notifications = client.get("/notifications", params={"user_id": reviewer["id"]})
        assert notifications.status_code == 200
        assert notifications.json()[0]["document_id"] == document["id"]
