"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft

from conftest import create_document, review_document, submit_document

# =============================================================================
# Feature: 5: Edge Cases
# ID: feature-5-edge-cases
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="concurrent-approval-and-rejection-by-different-reviewers",
)
def test_concurrent_approval_and_rejection_by_different_reviewers(
    client, author, reviewer, additional_reviewer
):
    """Concurrent approval and rejection by different reviewers

    Priority: medium
    """
    with specleft.step('Given a document in "review" status with multiple reviewers'):
        document = create_document(
            client,
            author["id"],
            [reviewer["id"], additional_reviewer["id"]],
        )
        submit_document(client, document["id"], author["id"])

    with specleft.step("When one reviewer approves and another rejects simultaneously"):
        response = review_document(client, document["id"], reviewer["id"], "approve")
        assert response.status_code == 200
        response = review_document(
            client, document["id"], additional_reviewer["id"], "reject"
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step("Then the rejection takes precedence"):
        assert payload["status"] == "rejected"

    with specleft.step('And the document status changes to "rejected"'):
        assert payload["status"] == "rejected"


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="notes-4",
    skip=True,
    reason="Priority note only",
)
def test_notes_4():
    """Notes

    Priority: medium
    """


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="resubmit-rejected-document-creates-new-review-cycle",
)
def test_resubmit_rejected_document_creates_new_review_cycle(client, author, reviewer):
    """Resubmit rejected document creates new review cycle

    Priority: medium
    """
    with specleft.step('Given a document in "rejected" status'):
        document = create_document(client, author["id"], [reviewer["id"]])
        submit_document(client, document["id"], author["id"])
        response = review_document(
            client, document["id"], reviewer["id"], "reject", reason="No"
        )
        assert response.status_code == 200

    with specleft.step("When the author resubmits the document"):
        response = client.post(
            f"/documents/{document['id']}/resubmit",
            json={"author_id": author["id"], "reviewer_ids": [reviewer["id"]]},
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step('Then the document status changes to "review"'):
        assert payload["status"] == "review"

    with specleft.step(
        "And a new review cycle is created with fresh reviewer assignments"
    ):
        assert payload["current_cycle_id"] is not None
        assert len(payload["review_cycles"]) == 2

    with specleft.step("And previous review history is preserved"):
        assert payload["review_cycles"][0]["reviewers"][0]["decision"] == "reject"


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="reviewer-who-is-also-the-author-cannot-approve-own-document",
)
def test_reviewer_who_is_also_the_author_cannot_approve_own_document(client, author):
    """Reviewer who is also the author cannot approve own document

    Priority: medium
    """
    with specleft.step("Given a user who is both the author and an assigned reviewer"):
        document = create_document(client, author["id"], [author["id"]])
        submit_document(client, document["id"], author["id"])

    with specleft.step("When they attempt to approve the document"):
        response = review_document(client, document["id"], author["id"], "approve")

    with specleft.step("Then the approval is rejected"):
        assert response.status_code == 400

    with specleft.step(
        "And an error is returned indicating self-approval is not permitted"
    ):
        assert response.json()["detail"] == "self-approval not permitted"


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="submit-document-with-no-reviewers-assigned-returns-error",
)
def test_submit_document_with_no_reviewers_assigned_returns_error(client, author):
    """Submit document with no reviewers assigned returns error

    Priority: medium
    """
    with specleft.step('Given a document in "draft" status'):
        document = create_document(client, author["id"], [])

    with specleft.step(
        "When the author submits the document with no reviewers assigned"
    ):
        response = client.post(
            f"/documents/{document['id']}/submit", json={"author_id": author["id"]}
        )

    with specleft.step("Then the submission is rejected"):
        assert response.status_code == 400

    with specleft.step(
        "And an error is returned indicating at least one reviewer is required"
    ):
        assert response.json()["detail"] == "at least one reviewer is required"
