"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from datetime import datetime, timedelta

import main

from specleft import specleft

from conftest import create_document, escalate_document, submit_document

# =============================================================================
# Feature: 4: Escalation
# ID: feature-4-escalation
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-4-escalation",
    scenario_id="auto-escalate-after-configurable-timeout",
)
def test_auto_escalate_after_configurable_timeout(
    client, author, reviewer, additional_reviewer
):
    """Auto-escalate after configurable timeout

    Priority: medium
    """
    with specleft.step('Given a document in "review" status'):
        document = create_document(
            client,
            author["id"],
            [reviewer["id"]],
            escalation_chain=[additional_reviewer["id"]],
            escalation_timeout_seconds=1,
        )
        submit_document(client, document["id"], author["id"])

    with specleft.step(
        "When the configured timeout period elapses without all reviewers acting"
    ):
        with main.SessionLocal.begin() as session:
            stored = session.get(main.Document, document["id"])
            assert stored is not None
            stored.next_escalation_at = datetime.utcnow() - timedelta(seconds=1)
        response = escalate_document(client, document["id"])
        assert response.status_code == 200
        payload = response.json()

    with specleft.step("Then the document is escalated to the next-level approver"):
        assert additional_reviewer["id"] in payload["reviewer_ids"]

    with specleft.step("And the escalation is recorded with a timestamp"):
        escalation = payload["review_cycles"][0]["escalations"][0]
        assert escalation["escalated_at"] is not None


@specleft(
    feature_id="feature-4-escalation",
    scenario_id="escalation-notifies-next-level-approver",
)
def test_escalation_notifies_next_level_approver(
    client, author, reviewer, additional_reviewer
):
    """Escalation notifies next-level approver

    Priority: medium
    """
    with specleft.step("Given a document that has been escalated"):
        document = create_document(
            client,
            author["id"],
            [reviewer["id"]],
            escalation_chain=[additional_reviewer["id"]],
            escalation_timeout_seconds=1,
        )
        submit_document(client, document["id"], author["id"])
        with main.SessionLocal.begin() as session:
            stored = session.get(main.Document, document["id"])
            assert stored is not None
            stored.next_escalation_at = datetime.utcnow() - timedelta(seconds=1)
        response = escalate_document(client, document["id"])
        assert response.status_code == 200

    with specleft.step("When the escalation is triggered"):
        notifications = client.get(
            "/notifications", params={"user_id": additional_reviewer["id"]}
        )
        assert notifications.status_code == 200

    with specleft.step("Then the next-level approver is added to the reviewer list"):
        reviewers = response.json()["reviewer_ids"]
        assert additional_reviewer["id"] in reviewers

    with specleft.step("And a notification is generated for the new approver"):
        assert notifications.json()[0]["document_id"] == document["id"]


@specleft(
    feature_id="feature-4-escalation",
    scenario_id="escalation-resets-timeout-for-new-approver",
)
def test_escalation_resets_timeout_for_new_approver(
    client, author, reviewer, additional_reviewer
):
    """Escalation resets timeout for new approver

    Priority: medium
    """
    with specleft.step("Given a document that has been escalated to a new approver"):
        document = create_document(
            client,
            author["id"],
            [reviewer["id"]],
            escalation_chain=[additional_reviewer["id"]],
            escalation_timeout_seconds=1,
        )
        submit_document(client, document["id"], author["id"])
        with main.SessionLocal.begin() as session:
            stored = session.get(main.Document, document["id"])
            assert stored is not None
            stored.next_escalation_at = datetime.utcnow() - timedelta(seconds=1)
        response = escalate_document(client, document["id"])
        assert response.status_code == 200
        payload = response.json()

    with specleft.step("When the escalation is processed"):
        with main.SessionLocal() as session:
            stored = session.get(main.Document, document["id"])
            assert stored is not None
            updated_timeout = stored.next_escalation_at

    with specleft.step("Then a new timeout period begins for the escalated approver"):
        assert updated_timeout is not None

    with specleft.step("And the original timeout is no longer active"):
        assert payload["status"] == "review"


@specleft(
    feature_id="feature-4-escalation",
    scenario_id="notes-3",
    skip=True,
    reason="Priority note only",
)
def test_notes_3():
    """Notes

    Priority: high
    """


@specleft(
    feature_id="feature-4-escalation",
    scenario_id="original-reviewer-can-still-approve-before-escalation-triggers",
)
def test_original_reviewer_can_still_approve_before_escalation_triggers(
    client, author, reviewer, additional_reviewer
):
    """Original reviewer can still approve before escalation triggers

    Priority: medium
    """
    with specleft.step("Given a document approaching the escalation timeout"):
        document = create_document(
            client,
            author["id"],
            [reviewer["id"]],
            escalation_chain=[additional_reviewer["id"]],
            escalation_timeout_seconds=3600,
        )
        submit_document(client, document["id"], author["id"])

    with specleft.step(
        "When the original reviewer submits their decision before the timeout"
    ):
        response = client.post(
            f"/documents/{document['id']}/review",
            json={"actor_id": reviewer["id"], "decision": "approve"},
        )
        assert response.status_code == 200
        payload = response.json()

    with specleft.step("Then the escalation is cancelled"):
        assert payload["status"] == "approved"

    with specleft.step("And the document proceeds through normal approval flow"):
        with main.SessionLocal() as session:
            stored = session.get(main.Document, document["id"])
            assert stored is not None
            assert stored.next_escalation_at is None
