"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft

from tests.helpers import (
    assert_error,
    approve_document,
    create_document,
    get_document,
    reject_document,
    submit_document,
)

# =============================================================================
# Feature: 5: Edge Cases
# ID: feature-5-edge-cases
# --- confidence: medium source: prd assumptions: - Concurrent decisions are resolved deterministically by database transaction ordering. - Rejected documents keep previous review history. tags: - edge-cases - workflow component: api ---
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="concurrent-approval-and-rejection-by-different-reviewers",
)
def test_concurrent_approval_and_rejection_by_different_reviewers(client):
    """Concurrent approval and rejection by different reviewers

    Priority: medium
    """
    with specleft.step('Given a document in "review" status with multiple reviewers'):
        author_id = "author-1"
        reviewer_ids = ["reviewer-1", "reviewer-2"]
        document_id = create_document(client, author_id=author_id).json()["id"]
        submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=reviewer_ids,
        )

    with specleft.step("When one reviewer approves and another rejects simultaneously"):
        approve_response = approve_document(
            client,
            document_id=document_id,
            actor_id=reviewer_ids[0],
        )
        reject_response = reject_document(
            client,
            document_id=document_id,
            actor_id=reviewer_ids[1],
            reason="Incorrect",
        )
        assert approve_response.status_code == 200
        assert reject_response.status_code == 200

    with specleft.step("Then the rejection takes precedence"):
        fetch_response = get_document(client, document_id=document_id)
        assert fetch_response.json()["status"] == "rejected"

    with specleft.step('And the document status changes to "rejected"'):
        assert fetch_response.json()["status"] == "rejected"


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="notes-4",
)
def test_notes_4(client):
    """Notes

    Priority: medium
    """
    with specleft.step("Then conflict resolution rules are deterministic"):
        author_id = "author-1"
        reviewer_ids = ["reviewer-1", "reviewer-2"]
        document_id = create_document(client, author_id=author_id).json()["id"]
        submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=reviewer_ids,
        )
        approve_document(client, document_id=document_id, actor_id=reviewer_ids[0])
        reject_document(
            client,
            document_id=document_id,
            actor_id=reviewer_ids[1],
            reason="No",
        )
        fetch_response = get_document(client, document_id=document_id)
        assert fetch_response.json()["status"] == "rejected"

    with specleft.step("And all edge case handling returns descriptive error messages"):
        approve_response = approve_document(
            client,
            document_id=document_id,
            actor_id=reviewer_ids[0],
        )
        assert_error(approve_response, status_code=409, code="review_decision_exists")


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="resubmit-rejected-document-creates-new-review-cycle",
)
def test_resubmit_rejected_document_creates_new_review_cycle(client):
    """Resubmit rejected document creates new review cycle

    Priority: medium
    """
    with specleft.step('Given a document in "rejected" status'):
        author_id = "author-1"
        reviewer_id = "reviewer-1"
        document_id = create_document(client, author_id=author_id).json()["id"]
        submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=[reviewer_id],
        )
        reject_document(
            client,
            document_id=document_id,
            actor_id=reviewer_id,
            reason="Needs work",
        )

    with specleft.step("When the author resubmits the document"):
        resubmit_response = submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=["reviewer-2"],
        )
        assert resubmit_response.status_code == 200

    with specleft.step('Then the document status changes to "review"'):
        fetch_response = get_document(client, document_id=document_id)
        assert fetch_response.json()["status"] == "review"

    with specleft.step(
        "And a new review cycle is created with fresh reviewer assignments"
    ):
        assert fetch_response.json()["reviewer_ids"] == ["reviewer-2"]

    with specleft.step("And previous review history is preserved"):
        history_response = client.get(f"/documents/{document_id}/reviews")
        assert history_response.status_code == 200
        assert len(history_response.json()["items"]) >= 1


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="reviewer-who-is-also-the-author-cannot-approve-own-document",
)
def test_reviewer_who_is_also_the_author_cannot_approve_own_document(client):
    """Reviewer who is also the author cannot approve own document

    Priority: medium
    """
    with specleft.step("Given a user who is both the author and an assigned reviewer"):
        author_id = "author-1"
        document_id = create_document(client, author_id=author_id).json()["id"]
        submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=[author_id],
        )

    with specleft.step("When they attempt to approve the document"):
        approve_response = approve_document(
            client,
            document_id=document_id,
            actor_id=author_id,
        )

    with specleft.step("Then the approval is rejected"):
        assert_error(approve_response, status_code=403, code="self_approval_forbidden")

    with specleft.step(
        "And an error is returned indicating self-approval is not permitted"
    ):
        assert "self" in approve_response.json()["error"]["message"].lower()


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="submit-document-with-no-reviewers-assigned-returns-error",
)
def test_submit_document_with_no_reviewers_assigned_returns_error(client):
    """Submit document with no reviewers assigned returns error

    Priority: medium
    """
    with specleft.step('Given a document in "draft" status'):
        author_id = "author-1"
        document_id = create_document(client, author_id=author_id).json()["id"]

    with specleft.step(
        "When the author submits the document with no reviewers assigned"
    ):
        submit_response = submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=[],
        )

    with specleft.step("Then the submission is rejected"):
        assert_error(submit_response, status_code=400, code="reviewers_required")

    with specleft.step(
        "And an error is returned indicating at least one reviewer is required"
    ):
        assert "reviewer" in submit_response.json()["error"]["message"].lower()
