"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

import pytest
from datetime import datetime, timedelta, timezone

from specleft import specleft
from tests.helpers import create_and_submit_document

# =============================================================================
# Feature: 3: Delegation
# ID: feature-3-delegation
# Reviewers may delegate their review responsibility to a substitute.
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="delegate-review-to-substitute-with-expiry-date",
)
def test_delegate_review_to_substitute_with_expiry_date(client):
    """Delegate review to substitute with expiry date

    Priority: high
    """
    with specleft.step("Given a reviewer assigned to a document"):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])
        expires = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()

    with specleft.step("When they delegate to a substitute with an expiry date"):
        resp = client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "reviewer-1",
                "substitute_id": "substitute-1",
                "expires_at": expires,
            },
        )

    with specleft.step(
        "Then the substitute is granted review permissions for that document"
    ):
        assert resp.status_code == 201
        data = resp.json()
        assert data["substitute_id"] == "substitute-1"

    with specleft.step("And the delegation record includes the expiry timestamp"):
        assert data["expires_at"] is not None
        assert data["revoked"] is False


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="substitute-can-approve-on-behalf-of-delegator",
)
def test_substitute_can_approve_on_behalf_of_delegator(client):
    """Substitute can approve on behalf of delegator

    Priority: high
    """
    with specleft.step("Given a valid delegation that has not expired"):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])
        expires = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
        client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "reviewer-1",
                "substitute_id": "substitute-1",
                "expires_at": expires,
            },
        )

    with specleft.step("When the substitute approves the document"):
        resp = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "substitute-1",
                "decision": "approved",
            },
        )

    with specleft.step(
        "Then the approval is recorded as the substitute acting on behalf of the delegator"
    ):
        assert resp.status_code == 200
        history = client.get(f"/api/documents/{doc['id']}/history").json()
        assert history[0]["reviewer_id"] == "substitute-1"
        assert history[0]["on_behalf_of"] == "reviewer-1"

    with specleft.step("And the delegator's review requirement is satisfied"):
        doc_resp = client.get(f"/api/documents/{doc['id']}").json()
        assert doc_resp["status"] == "approved"


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="expired-delegation-is-rejected",
)
def test_expired_delegation_is_rejected(client):
    """Expired delegation is rejected

    Priority: high
    """
    with specleft.step("Given a delegation that has passed its expiry date"):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])
        expired = (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat()
        client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "reviewer-1",
                "substitute_id": "substitute-1",
                "expires_at": expired,
            },
        )

    with specleft.step("When the substitute attempts to approve the document"):
        resp = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "substitute-1",
                "decision": "approved",
            },
        )

    with specleft.step("Then the approval is rejected"):
        assert resp.status_code == 403

    with specleft.step(
        "And an error is returned indicating the delegation has expired"
    ):
        assert "not an assigned reviewer" in resp.json()["detail"].lower()


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="delegator-can-revoke-delegation-before-expiry",
)
def test_delegator_can_revoke_delegation_before_expiry(client):
    """Delegator can revoke delegation before expiry

    Priority: high
    """
    with specleft.step("Given an active delegation"):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])
        expires = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
        client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "reviewer-1",
                "substitute_id": "substitute-1",
                "expires_at": expires,
            },
        )

    with specleft.step("When the delegator revokes the delegation"):
        resp = client.post(
            f"/api/documents/{doc['id']}/delegate/revoke",
            json={
                "delegator_id": "reviewer-1",
            },
        )
        assert resp.status_code == 200
        assert resp.json()["revoked"] is True

    with specleft.step("Then the substitute loses review permissions immediately"):
        review_resp = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "substitute-1",
                "decision": "approved",
            },
        )
        assert review_resp.status_code == 403

    with specleft.step("And subsequent actions by the substitute are rejected"):
        assert "not an assigned reviewer" in review_resp.json()["detail"].lower()


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="prevent-delegation-chain",
)
def test_prevent_delegation_chain(client):
    """Prevent delegation chain

    Priority: high
    """
    with specleft.step("Given a substitute who has been delegated review authority"):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])
        expires = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
        client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "reviewer-1",
                "substitute_id": "substitute-1",
                "expires_at": expires,
            },
        )

    with specleft.step("When the substitute attempts to delegate to another person"):
        resp = client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "substitute-1",
                "substitute_id": "substitute-2",
                "expires_at": expires,
            },
        )

    with specleft.step("Then the delegation is rejected"):
        assert resp.status_code == 403

    with specleft.step(
        "And an error is returned indicating re-delegation is not permitted"
    ):
        assert "re-delegation" in resp.json()["detail"].lower()


@specleft(
    feature_id="feature-3-delegation",
    scenario_id="one-active-delegation-per-reviewer-per-document",
)
def test_one_active_delegation_per_reviewer_per_document(client):
    """One active delegation per reviewer per document

    Priority: high
    """
    with specleft.step(
        "Given a reviewer with an existing active delegation for a document"
    ):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])
        expires = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
        resp1 = client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "reviewer-1",
                "substitute_id": "substitute-1",
                "expires_at": expires,
            },
        )
        assert resp1.status_code == 201

    with specleft.step(
        "When they attempt to create another delegation for the same document"
    ):
        resp2 = client.post(
            f"/api/documents/{doc['id']}/delegate",
            json={
                "delegator_id": "reviewer-1",
                "substitute_id": "substitute-2",
                "expires_at": expires,
            },
        )

    with specleft.step("Then the delegation is rejected"):
        assert resp2.status_code == 409

    with specleft.step(
        "And an error is returned indicating an active delegation already exists"
    ):
        assert "active delegation already exists" in resp2.json()["detail"].lower()
