"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

import pytest

from specleft import specleft
from tests.helpers import (
    create_and_submit_document,
    approve_document,
    reject_document,
)

# =============================================================================
# Feature: 2: Multi-Reviewer Approval
# ID: feature-2-multi-reviewer-approval
# Documents may require approval from multiple reviewers before being considered approved.
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="require-all-assigned-reviewers-to-approve",
)
def test_require_all_assigned_reviewers_to_approve(client):
    """Require all assigned reviewers to approve

    Priority: critical
    """
    with specleft.step(
        'Given a document in "review" status with three assigned reviewers'
    ):
        doc = create_and_submit_document(
            client, reviewer_ids=["reviewer-1", "reviewer-2", "reviewer-3"]
        )

    with specleft.step("When only two reviewers have approved"):
        approve_document(client, doc["id"], "reviewer-1")
        approve_document(client, doc["id"], "reviewer-2")

    with specleft.step('Then the document remains in "review" status'):
        resp = client.get(f"/api/documents/{doc['id']}")
        assert resp.json()["status"] == "review"

    with specleft.step("And the pending reviewer is visible in the status response"):
        status = client.get(f"/api/documents/{doc['id']}/status").json()
        assert "reviewer-3" in status["pending_reviewers"]


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="reject-if-any-reviewer-rejects",
)
def test_reject_if_any_reviewer_rejects(client):
    """Reject if any reviewer rejects

    Priority: critical
    """
    with specleft.step('Given a document in "review" status with multiple reviewers'):
        doc = create_and_submit_document(
            client, reviewer_ids=["reviewer-1", "reviewer-2", "reviewer-3"]
        )

    with specleft.step("When one reviewer rejects the document"):
        resp = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "rejected",
                "reason": "Does not meet standards",
            },
        )
        assert resp.status_code == 200

    with specleft.step('Then the document status changes to "rejected"'):
        data = resp.json()
        assert data["status"] == "rejected"

    with specleft.step("And remaining reviewers are no longer required to act"):
        status = client.get(f"/api/documents/{doc['id']}/status").json()
        assert status["status"] == "rejected"


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="track-individual-reviewer-decisions-with-timestamps",
)
def test_track_individual_reviewer_decisions_with_timestamps(client):
    """Track individual reviewer decisions with timestamps

    Priority: critical
    """
    with specleft.step('Given a document in "review" status'):
        doc = create_and_submit_document(
            client, reviewer_ids=["reviewer-1", "reviewer-2"]
        )

    with specleft.step("When a reviewer submits their decision"):
        client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "approved",
            },
        )

    with specleft.step(
        "Then the decision is recorded with the reviewer ID and timestamp"
    ):
        history = client.get(f"/api/documents/{doc['id']}/history").json()
        assert len(history) == 1
        assert history[0]["reviewer_id"] == "reviewer-1"
        assert history[0]["decided_at"] is not None

    with specleft.step("And the decision is visible in the document review history"):
        assert history[0]["decision"] == "approved"


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="prevent-duplicate-approval-from-same-reviewer",
)
def test_prevent_duplicate_approval_from_same_reviewer(client):
    """Prevent duplicate approval from same reviewer

    Priority: critical
    """
    with specleft.step("Given a reviewer who has already approved a document"):
        doc = create_and_submit_document(
            client, reviewer_ids=["reviewer-1", "reviewer-2"]
        )
        resp1 = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "approved",
            },
        )
        assert resp1.status_code == 200

    with specleft.step("When they attempt to approve the same document again"):
        resp2 = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "approved",
            },
        )

    with specleft.step("Then the request is rejected"):
        assert resp2.status_code == 409

    with specleft.step(
        "And an error is returned indicating they have already submitted a decision"
    ):
        assert "already submitted" in resp2.json()["detail"].lower()


@specleft(
    feature_id="feature-2-multi-reviewer-approval",
    scenario_id="reviewer-decisions-are-immutable",
)
def test_reviewer_decisions_are_immutable(client):
    """Reviewer decisions are immutable

    Priority: high
    """
    with specleft.step("Given a reviewer who has already approved a document"):
        doc = create_and_submit_document(
            client, reviewer_ids=["reviewer-1", "reviewer-2"]
        )
        resp1 = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "approved",
            },
        )
        assert resp1.status_code == 200

    with specleft.step("When they attempt to reject the same document"):
        resp2 = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "rejected",
                "reason": "Changed my mind",
            },
        )

    with specleft.step("Then the request is rejected"):
        assert resp2.status_code == 409

    with specleft.step(
        "And an error is returned indicating their decision cannot be changed"
    ):
        assert "already submitted" in resp2.json()["detail"].lower()
