"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

import pytest

from specleft import specleft
from tests.helpers import (
    create_draft_document,
    create_and_submit_document,
    approve_document,
    reject_document,
)

# =============================================================================
# Feature: 5: Edge Cases
# ID: feature-5-edge-cases
# Boundary conditions and conflict resolution for the approval workflow.
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="concurrent-approval-and-rejection-by-different-reviewers",
)
def test_concurrent_approval_and_rejection_by_different_reviewers(client):
    """Concurrent approval and rejection by different reviewers

    Priority: medium
    """
    with specleft.step('Given a document in "review" status with multiple reviewers'):
        doc = create_and_submit_document(
            client, reviewer_ids=["reviewer-1", "reviewer-2"]
        )

    with specleft.step("When one reviewer approves and another rejects simultaneously"):
        resp1 = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "approved",
            },
        )
        assert resp1.status_code == 200

        resp2 = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-2",
                "decision": "rejected",
                "reason": "Does not meet standards",
            },
        )
        assert resp2.status_code == 200

    with specleft.step("Then the rejection takes precedence"):
        final = client.get(f"/api/documents/{doc['id']}").json()
        assert final["status"] == "rejected"

    with specleft.step('And the document status changes to "rejected"'):
        assert final["status"] == "rejected"


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="submit-document-with-no-reviewers-assigned-returns-error",
)
def test_submit_document_with_no_reviewers_assigned_returns_error(client):
    """Submit document with no reviewers assigned returns error

    Priority: medium
    """
    with specleft.step('Given a document in "draft" status'):
        doc = create_draft_document(client)

    with specleft.step(
        "When the author submits the document with no reviewers assigned"
    ):
        resp = client.post(
            f"/api/documents/{doc['id']}/submit",
            json={
                "reviewer_ids": [],
            },
        )

    with specleft.step("Then the submission is rejected"):
        assert resp.status_code == 400

    with specleft.step(
        "And an error is returned indicating at least one reviewer is required"
    ):
        assert "at least one reviewer" in resp.json()["detail"].lower()


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="reviewer-who-is-also-the-author-cannot-approve-own-document",
)
def test_reviewer_who_is_also_the_author_cannot_approve_own_document(client):
    """Reviewer who is also the author cannot approve own document

    Priority: medium
    """
    with specleft.step("Given a user who is both the author and an assigned reviewer"):
        doc = create_and_submit_document(
            client, author_id="user-1", reviewer_ids=["user-1", "reviewer-2"]
        )

    with specleft.step("When they attempt to approve the document"):
        resp = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "user-1",
                "decision": "approved",
            },
        )

    with specleft.step("Then the approval is rejected"):
        assert resp.status_code == 403

    with specleft.step(
        "And an error is returned indicating self-approval is not permitted"
    ):
        assert "self-approval" in resp.json()["detail"].lower()


@specleft(
    feature_id="feature-5-edge-cases",
    scenario_id="resubmit-rejected-document-creates-new-review-cycle",
)
def test_resubmit_rejected_document_creates_new_review_cycle(client):
    """Resubmit rejected document creates new review cycle

    Priority: medium
    """
    with specleft.step('Given a document in "rejected" status'):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])
        reject_document(client, doc["id"], "reviewer-1", reason="Needs work")
        doc_state = client.get(f"/api/documents/{doc['id']}").json()
        assert doc_state["status"] == "rejected"

    with specleft.step("When the author resubmits the document"):
        resp = client.post(
            f"/api/documents/{doc['id']}/submit",
            json={
                "reviewer_ids": ["reviewer-1"],
            },
        )

    with specleft.step('Then the document status changes to "review"'):
        assert resp.status_code == 200
        assert resp.json()["status"] == "review"

    with specleft.step(
        "And a new review cycle is created with fresh reviewer assignments"
    ):
        status = client.get(f"/api/documents/{doc['id']}/status").json()
        assert "reviewer-1" in status["pending_reviewers"]

    with specleft.step("And previous review history is preserved"):
        history = client.get(f"/api/documents/{doc['id']}/history").json()
        cycle_1_decisions = [d for d in history if d["review_cycle"] == 1]
        assert len(cycle_1_decisions) == 1
        assert cycle_1_decisions[0]["decision"] == "rejected"
