"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

import pytest

from specleft import specleft

from tests.helpers import (
    assert_error,
    create_document,
    get_document,
    submit_document,
    update_document,
)

# =============================================================================
# Feature: 1: Document Lifecycle
# ID: feature-1-document-lifecycle
# --- confidence: medium source: prd assumptions: - System uses REST-style HTTP endpoints. - Users are represented by UUIDs passed in requests (no auth system). - Notifications are recorded in a log table, not delivered externally. tags: - documents - workflow component: api ---
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="approve-document-with-single-reviewer",
)
def test_approve_document_with_single_reviewer(client):
    """Approve document with single reviewer

    Priority: medium
    """
    with specleft.step(
        'Given a document in "review" status with one assigned reviewer'
    ):
        author_id = "author-1"
        reviewer_id = "reviewer-1"
        create_response = create_document(client, author_id=author_id)
        assert create_response.status_code == 201
        document_id = create_response.json()["id"]
        submit_response = submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=[reviewer_id],
        )
        assert submit_response.status_code == 200

    with specleft.step("When the reviewer approves the document"):
        approve_response = client.post(
            f"/documents/{document_id}/reviews/approve",
            json={"actor_id": reviewer_id},
        )
        assert approve_response.status_code == 200
        approval_payload = approve_response.json()

    with specleft.step('Then the document status changes to "approved"'):
        fetch_response = get_document(client, document_id=document_id)
        assert fetch_response.status_code == 200
        assert fetch_response.json()["status"] == "approved"

    with specleft.step("And the approval is recorded with a timestamp"):
        assert approval_payload["decision"]["status"] == "approved"
        assert approval_payload["decision"]["reviewer_id"] == reviewer_id
        assert approval_payload["decision"]["decided_at"]


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="create-document-as-draft",
)
def test_create_document_as_draft(client):
    """Create document as draft

    Priority: medium
    """
    with specleft.step("Given a user with author permissions"):
        author_id = "author-1"

    with specleft.step("When they create a new document"):
        response = create_document(
            client, author_id=author_id, title="Policy", content="Draft"
        )

    with specleft.step('Then the document is created with status "draft"'):
        assert response.status_code == 201
        payload = response.json()
        assert payload["status"] == "draft"

    with specleft.step("And the document is assigned to the author"):
        assert payload["author_id"] == author_id


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="notes",
)
def test_notes():
    """Notes

    Priority: critical
    """
    pytest.skip("Covered by API transaction tests")


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="prevent-edits-to-approved-documents",
)
def test_prevent_edits_to_approved_documents(client):
    """Prevent edits to approved documents

    Priority: medium
    """
    with specleft.step('Given a document in "approved" status'):
        author_id = "author-1"
        reviewer_id = "reviewer-1"
        create_response = create_document(client, author_id=author_id)
        document_id = create_response.json()["id"]
        submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=[reviewer_id],
        )
        approve_response = client.post(
            f"/documents/{document_id}/reviews/approve",
            json={"actor_id": reviewer_id},
        )
        assert approve_response.status_code == 200

    with specleft.step("When any user attempts to edit the document"):
        update_response = update_document(
            client,
            document_id=document_id,
            editor_id="editor-1",
            title="Updated",
            content="Updated",
        )

    with specleft.step("Then the edit is rejected"):
        assert_error(update_response, status_code=409, code="document_locked")

    with specleft.step("And an error is returned indicating the document is locked"):
        assert "locked" in update_response.json()["error"]["message"].lower()


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="prevent-edits-to-documents-under-review",
)
def test_prevent_edits_to_documents_under_review(client):
    """Prevent edits to documents under review

    Priority: medium
    """
    with specleft.step('Given a document in "review" status'):
        author_id = "author-1"
        reviewer_id = "reviewer-1"
        create_response = create_document(client, author_id=author_id)
        document_id = create_response.json()["id"]
        submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=[reviewer_id],
        )

    with specleft.step("When the author attempts to edit the document"):
        update_response = update_document(
            client,
            document_id=document_id,
            editor_id=author_id,
            title="Updated",
            content="Updated",
        )

    with specleft.step("Then the edit is rejected"):
        assert_error(update_response, status_code=409, code="document_under_review")

    with specleft.step(
        "And an error is returned indicating the document is under review"
    ):
        assert "under review" in update_response.json()["error"]["message"].lower()


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="reject-document-with-reason",
)
def test_reject_document_with_reason(client):
    """Reject document with reason

    Priority: medium
    """
    with specleft.step('Given a document in "review" status'):
        author_id = "author-1"
        reviewer_id = "reviewer-1"
        create_response = create_document(client, author_id=author_id)
        document_id = create_response.json()["id"]
        submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=[reviewer_id],
        )

    with specleft.step("When a reviewer rejects the document"):
        reject_response = client.post(
            f"/documents/{document_id}/reviews/reject",
            json={"actor_id": reviewer_id, "reason": "Insufficient details"},
        )
        assert reject_response.status_code == 200
        reject_payload = reject_response.json()

    with specleft.step('Then the document status changes to "rejected"'):
        fetch_response = get_document(client, document_id=document_id)
        assert fetch_response.json()["status"] == "rejected"

    with specleft.step("And the rejection reason is recorded"):
        assert reject_payload["decision"]["status"] == "rejected"
        assert reject_payload["decision"]["reason"] == "Insufficient details"
        assert reject_payload["decision"]["decided_at"]


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="submit-document-for-review",
)
def test_submit_document_for_review(client):
    """Submit document for review

    Priority: medium
    """
    with specleft.step('Given a document in "draft" status'):
        author_id = "author-1"
        reviewer_ids = ["reviewer-1", "reviewer-2"]
        create_response = create_document(client, author_id=author_id)
        document_id = create_response.json()["id"]

    with specleft.step("When the author submits it for review"):
        submit_response = submit_document(
            client,
            document_id=document_id,
            author_id=author_id,
            reviewer_ids=reviewer_ids,
        )

    with specleft.step('Then the document status changes to "review"'):
        assert submit_response.status_code == 200
        fetch_response = get_document(client, document_id=document_id)
        assert fetch_response.json()["status"] == "review"

    with specleft.step("And all assigned reviewers are notified"):
        notification_response = client.get(f"/documents/{document_id}/notifications")
        assert notification_response.status_code == 200
        notification_payload = notification_response.json()
        notified = {item["recipient_id"] for item in notification_payload["items"]}
        assert set(reviewer_ids).issubset(notified)
