"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

import pytest

from specleft import specleft
from tests.helpers import (
    create_draft_document,
    submit_document,
    approve_document,
    reject_document,
    create_and_submit_document,
    get_approved_document,
)

# =============================================================================
# Feature: 1: Document Lifecycle
# ID: feature-1-document-lifecycle
# Documents must follow a strict state machine through their approval process.
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="create-document-as-draft",
)
def test_create_document_as_draft(client):
    """Create document as draft

    Priority: critical
    """
    with specleft.step("Given a user with author permissions"):
        author_id = "author-1"

    with specleft.step("When they create a new document"):
        resp = client.post(
            "/api/documents",
            json={
                "title": "My Document",
                "body": "Some content",
                "author_id": author_id,
            },
        )

    with specleft.step('Then the document is created with status "draft"'):
        assert resp.status_code == 201
        data = resp.json()
        assert data["status"] == "draft"

    with specleft.step("And the document is assigned to the author"):
        assert data["author_id"] == author_id


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="submit-document-for-review",
)
def test_submit_document_for_review(client):
    """Submit document for review

    Priority: critical
    """
    with specleft.step('Given a document in "draft" status'):
        doc = create_draft_document(client)
        assert doc["status"] == "draft"

    with specleft.step("When the author submits it for review"):
        resp = client.post(
            f"/api/documents/{doc['id']}/submit",
            json={
                "reviewer_ids": ["reviewer-1", "reviewer-2"],
            },
        )

    with specleft.step('Then the document status changes to "review"'):
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "review"

    with specleft.step("And all assigned reviewers are notified"):
        status = client.get(f"/api/documents/{doc['id']}/status").json()
        assert "reviewer-1" in status["reviewers"]
        assert "reviewer-2" in status["reviewers"]


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="approve-document-with-single-reviewer",
)
def test_approve_document_with_single_reviewer(client):
    """Approve document with single reviewer

    Priority: critical
    """
    with specleft.step(
        'Given a document in "review" status with one assigned reviewer'
    ):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])

    with specleft.step("When the reviewer approves the document"):
        resp = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "approved",
            },
        )

    with specleft.step('Then the document status changes to "approved"'):
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "approved"

    with specleft.step("And the approval is recorded with a timestamp"):
        history = client.get(f"/api/documents/{doc['id']}/history").json()
        assert len(history) == 1
        assert history[0]["decision"] == "approved"
        assert history[0]["decided_at"] is not None


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="reject-document-with-reason",
)
def test_reject_document_with_reason(client):
    """Reject document with reason

    Priority: critical
    """
    with specleft.step('Given a document in "review" status'):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])

    with specleft.step("When a reviewer rejects the document"):
        resp = client.post(
            f"/api/documents/{doc['id']}/review",
            json={
                "reviewer_id": "reviewer-1",
                "decision": "rejected",
                "reason": "Needs more detail",
            },
        )

    with specleft.step('Then the document status changes to "rejected"'):
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "rejected"

    with specleft.step("And the rejection reason is recorded"):
        history = client.get(f"/api/documents/{doc['id']}/history").json()
        assert history[0]["reason"] == "Needs more detail"


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="prevent-edits-to-approved-documents",
)
def test_prevent_edits_to_approved_documents(client):
    """Prevent edits to approved documents

    Priority: critical
    """
    with specleft.step('Given a document in "approved" status'):
        doc = get_approved_document(client)

    with specleft.step("When any user attempts to edit the document"):
        resp = client.put(f"/api/documents/{doc['id']}", json={"title": "New Title"})

    with specleft.step("Then the edit is rejected"):
        assert resp.status_code == 409

    with specleft.step("And an error is returned indicating the document is locked"):
        assert (
            "locked" in resp.json()["detail"].lower()
            or "approved" in resp.json()["detail"].lower()
        )


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="prevent-edits-to-documents-under-review",
)
def test_prevent_edits_to_documents_under_review(client):
    """Prevent edits to documents under review

    Priority: critical
    """
    with specleft.step('Given a document in "review" status'):
        doc = create_and_submit_document(client, reviewer_ids=["reviewer-1"])

    with specleft.step("When the author attempts to edit the document"):
        resp = client.put(f"/api/documents/{doc['id']}", json={"title": "New Title"})

    with specleft.step("Then the edit is rejected"):
        assert resp.status_code == 409

    with specleft.step(
        "And an error is returned indicating the document is under review"
    ):
        assert "under review" in resp.json()["detail"].lower()


@specleft(
    feature_id="feature-1-document-lifecycle",
    scenario_id="invalid-state-transitions-return-errors",
)
def test_invalid_state_transitions_return_errors(client):
    """Invalid state transitions return errors

    Priority: critical
    """
    with specleft.step('Given a document in "approved" status'):
        doc = get_approved_document(client)

    with specleft.step("When any user attempts to submit it for review"):
        resp = client.post(
            f"/api/documents/{doc['id']}/submit",
            json={
                "reviewer_ids": ["reviewer-2"],
            },
        )

    with specleft.step("Then the transition is rejected"):
        assert resp.status_code == 409

    with specleft.step(
        "And a descriptive error is returned indicating the transition is not allowed"
    ):
        assert "not allowed" in resp.json()["detail"].lower()
